name: cypress tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: pnpm/action-setup@v2.2.1
        with:
         version: 6.32.2
      - name: antd-desigin init
        run : |
          cd /packages/ant-design
      - name: E2E on Chrome
        uses: actions/checkout@v3
      - name: Test
        run: pnpm test:antd
