name: cypress tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: pnpm/action-setup@v2.2.1
        with:
         version: 6.32.2
      - name: E2E on Chrome
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          component: true
